"""
CR@CK TH3 B0X — Mission Data (Question Bank)
Each difficulty has 3 levels, each level has 10 questions.
type "output" -> user predicts what a code snippet prints (graded by text match)
type "code"   -> user writes code, graded by executing it and checking stdout/vars
"""

def _out(title, briefing, code, sample_output, accepted, hint=""):
    return {
        "title": title, "briefing": briefing, "type": "output",
        "code_snippet": code, "sample_output": sample_output,
        "accepted_answers": [a.strip().lower() for a in accepted], "hint": hint,
    }


def _code(title, briefing, task, sample_output, starter, check, hint=""):
    return {
        "title": title, "briefing": briefing, "type": "code",
        "task": task, "sample_output": sample_output,
        "starter_code": starter, "check": check, "hint": hint,
    }


QUESTIONS = {
    "Beginner": {
        1: [
            _out("The First Signal", "Decrypt the terminal's opening transmission.",
                 'print("Hello, Hacker")', "e.g. Hello, Hacker", ["Hello, Hacker"]),
            _out("Data Types", "Identify the payload type.",
                 'x = 42\nprint(type(x))', "e.g. <class 'int'>", ["<class 'int'>"]),
            _out("Variable Vault", "Trace the variable swap.",
                 'a, b = 5, 10\na, b = b, a\nprint(a, b)', "e.g. 10 5", ["10 5"]),
            _out("Arithmetic Cipher", "Compute the encryption key.",
                 'print(7 + 3 * 2)', "e.g. 13", ["13"]),
            _out("String Splice", "Reveal the hidden substring.",
                 's = "cracktheB0X"\nprint(s[0:5])', "e.g. crack", ["crack"]),
            _out("Boolean Gate", "Check the access gate logic.",
                 'print(5 > 3 and 2 == 2)', "e.g. True", ["True"]),
            _code("Access Code Generator", "Write code that prints your agent codename.",
                  'Assign a string "AGENT007" to a variable named codename and print it.',
                  "e.g. AGENT007", "codename = \n",
                  lambda stdout, ns: stdout.strip() == "AGENT007",
                  "Use print(codename)."),
            _out("Length Check", "Measure the intercepted string.",
                 'print(len("firewall"))', "e.g. 8", ["8"]),
            _out("Type Cast", "Convert the payload.",
                 'print(int("15") + 5)', "e.g. 20", ["20"]),
            _code("Input Simulation", "Print a formatted greeting using an f-string.",
                  'Create variable name="Neo" and print f"Welcome, {name}" exactly.',
                  "e.g. Welcome, Neo", "name = \n",
                  lambda stdout, ns: stdout.strip() == "Welcome, Neo",
                  'Use f"Welcome, {name}"'),
        ],
        2: [
            _out("Loop Breach", "Trace the for-loop's output.",
                 'for i in range(3):\n    print(i)', "e.g. 0\\n1\\n2", ["0 1 2", "0\n1\n2"]),
            _out("While Watchdog", "Trace the while loop.",
                 'i = 0\nwhile i < 3:\n    i += 1\nprint(i)', "e.g. 3", ["3"]),
            _out("Conditional Lock", "Determine which branch fires.",
                 'x = 10\nif x > 5:\n    print("open")\nelse:\n    print("locked")',
                 "e.g. open", ["open"]),
            _out("List Intel", "Trace list indexing.",
                 'l = [1,2,3,4]\nprint(l[-1])', "e.g. 4", ["4"]),
            _out("List Append", "Trace the mutated list.",
                 'l = [1,2]\nl.append(3)\nprint(l)', "e.g. [1, 2, 3]", ["[1, 2, 3]"]),
            _out("Dictionary Decode", "Extract the value.",
                 'd = {"user":"root","pass":"1234"}\nprint(d["user"])', "e.g. root", ["root"]),
            _out("String Format", "Trace the formatted string.",
                 'name="agent"\nprint(f"Hi {name.upper()}")', "e.g. Hi AGENT", ["Hi AGENT"]),
            _code("Sum Extractor", "Write a loop that sums numbers 1 to 5.",
                  'Use a for loop over range(1,6) to compute total and print(total).',
                  "e.g. 15", "total = 0\nfor i in range(1,6):\n    pass\nprint(total)",
                  lambda stdout, ns: stdout.strip() == "15"),
            _out("Nested Loop Trace", "Trace the nested loop.",
                 'for i in range(2):\n    for j in range(2):\n        print(i, j)',
                 "e.g. 0 0\\n0 1\\n1 0\\n1 1", ["0 0 0 1 1 0 1 1"]),
            _code("Even Filter", "Print only even numbers from 1 to 10 space-separated.",
                  'Loop 1..10, print each even number on same line separated by space.',
                  "e.g. 2 4 6 8 10", "for i in range(1,11):\n    pass",
                  lambda stdout, ns: stdout.split() == ["2", "4", "6", "8", "10"]),
        ],
        3: [
            _out("Function Uplink", "Trace the function's return.",
                 'def add(a,b):\n    return a+b\nprint(add(4,5))', "e.g. 9", ["9"]),
            _out("Default Params", "Trace the default argument.",
                 'def greet(name="Guest"):\n    return f"Hi {name}"\nprint(greet())',
                 "e.g. Hi Guest", ["Hi Guest"]),
            _out("Tuple Trap", "Identify the immutable structure output.",
                 't = (1,2,3)\nprint(t[1])', "e.g. 2", ["2"]),
            _out("Set Dedup", "Trace the set operation.",
                 's = set([1,1,2,2,3])\nprint(len(s))', "e.g. 3", ["3"]),
            _out("String Methods", "Trace the string transformation.",
                 'print("  breach  ".strip().upper())', "e.g. BREACH", ["BREACH"]),
            _out("List Comprehension", "Trace the comprehension output.",
                 'print([x*x for x in range(4)])', "e.g. [0, 1, 4, 9]", ["[0, 1, 4, 9]"]),
            _out("Exception Trace", "Trace the try/except output.",
                 'try:\n    print(1/0)\nexcept ZeroDivisionError:\n    print("caught")',
                 "e.g. caught", ["caught"]),
            _code("Function Builder", "Write a function is_even(n) and print result for 8.",
                  'Define is_even(n) returning True/False, then print(is_even(8)).',
                  "e.g. True", "def is_even(n):\n    pass\nprint(is_even(8))",
                  lambda stdout, ns: stdout.strip() == "True"),
            _out("Multiple Return", "Trace multiple return values.",
                 'def minmax(l):\n    return min(l), max(l)\nprint(minmax([4,1,9,3]))',
                 "e.g. (1, 9)", ["(1, 9)"]),
            _code("Palindrome Check", "Write code checking if 'level' is a palindrome.",
                  'Assign word="level", check word == word[::-1], print result.',
                  "e.g. True", "word = \"level\"\nprint()",
                  lambda stdout, ns: stdout.strip() == "True"),
        ],
    },
    "Intermediate": {
        1: [
            _out("Lambda Intercept", "Trace the lambda call.",
                 'f = lambda x: x*2\nprint(f(6))', "e.g. 12", ["12"]),
            _out("Map Operation", "Trace the mapped values.",
                 'print(list(map(lambda x: x+1, [1,2,3])))', "e.g. [2, 3, 4]", ["[2, 3, 4]"]),
            _out("Filter Operation", "Trace the filtered list.",
                 'print(list(filter(lambda x: x>2, [1,2,3,4])))', "e.g. [3, 4]", ["[3, 4]"]),
            _out("Dict Comprehension", "Trace the comprehension.",
                 'print({x: x*x for x in range(3)})', "e.g. {0: 0, 1: 1, 2: 4}",
                 ["{0: 0, 1: 1, 2: 4}"]),
            _out("*args Trace", "Trace the variadic function.",
                 'def total(*nums):\n    return sum(nums)\nprint(total(1,2,3))', "e.g. 6", ["6"]),
            _out("**kwargs Trace", "Trace the keyword arguments.",
                 'def info(**kw):\n    return kw["role"]\nprint(info(role="agent"))',
                 "e.g. agent", ["agent"]),
            _out("Class Blueprint", "Trace the object attribute access.",
                 'class Agent:\n    def __init__(self,name):\n        self.name=name\na=Agent("Neo")\nprint(a.name)',
                 "e.g. Neo", ["Neo"]),
            _code("Class Builder", "Create class Box with method reveal() returning 'unlocked'.",
                  'Define class Box with method reveal returning "unlocked"; instantiate and print(b.reveal()).',
                  "e.g. unlocked",
                  "class Box:\n    def reveal(self):\n        pass\nb = Box()\nprint(b.reveal())",
                  lambda stdout, ns: stdout.strip() == "unlocked"),
            _out("Inheritance Trace", "Trace the overridden method.",
                 'class A:\n    def hi(self): return "A"\nclass B(A):\n    def hi(self): return "B"\nprint(B().hi())',
                 "e.g. B", ["B"]),
            _out("Exception Custom", "Trace the raised exception message.",
                 'try:\n    raise ValueError("bad key")\nexcept ValueError as e:\n    print(e)',
                 "e.g. bad key", ["bad key"]),
        ],
        2: [
            _out("File Simulation", "Trace the mode string meaning (conceptual).",
                 '# "a" mode opens a file for:\nmode = "a"\nprint("append" if mode=="a" else "?")',
                 "e.g. append", ["append"]),
            _out("Generator Trace", "Trace the generator's first value.",
                 'def gen():\n    yield 1\n    yield 2\ng = gen()\nprint(next(g))', "e.g. 1", ["1"]),
            _out("Iterator Trace", "Trace manual iteration.",
                 'it = iter([10,20,30])\nprint(next(it), next(it))', "e.g. 10 20", ["10 20"]),
            _out("Decorator Trace", "Trace the decorated function output.",
                 'def deco(f):\n    def wrap():\n        return f()+"!"\n    return wrap\n@deco\ndef msg():\n    return "hi"\nprint(msg())',
                 "e.g. hi!", ["hi!"]),
            _out("Regex Match", "Trace the regex search result (True/False).",
                 'import re\nprint(bool(re.match(r"^[A-Z]+$", "HACK")))', "e.g. True", ["True"]),
            _out("String Join", "Trace the joined string.",
                 'print("-".join(["c","t","b"]))', "e.g. c-t-b", ["c-t-b"]),
            _out("Enumerate Trace", "Trace the enumerate output.",
                 'for i,v in enumerate(["x","y"]):\n    print(i,v)', "e.g. 0 x\\n1 y", ["0 x 1 y"]),
            _code("Sorting Agents", "Sort list [5,3,9,1] ascending and print it.",
                  'Use sorted() on the list [5,3,9,1] and print result.',
                  "e.g. [1, 3, 5, 9]", "nums = [5,3,9,1]\nprint()",
                  lambda stdout, ns: stdout.strip() == "[1, 3, 5, 9]"),
            _out("Zip Trace", "Trace the zipped pairs.",
                 'print(list(zip([1,2],["a","b"])))', "e.g. [(1, 'a'), (2, 'b')]",
                 ["[(1, 'a'), (2, 'b')]"]),
            _code("Word Counter", "Count words in the sentence 'the box is locked the box'.",
                  'Split the sentence, count occurrences of "the" using .count(), print the number.',
                  "e.g. 2",
                  "sentence = \"the box is locked the box\"\nwords = sentence.split()\nprint()",
                  lambda stdout, ns: stdout.strip() == "2"),
        ],
        3: [
            _out("Context Manager", "Trace the with-block behavior (conceptual).",
                 'class CM:\n    def __enter__(self): print("enter"); return self\n    def __exit__(self,*a): print("exit")\nwith CM():\n    print("inside")',
                 "e.g. enter\\ninside\\nexit", ["enter inside exit"]),
            _out("Closures", "Trace the closure's captured value.",
                 'def outer():\n    x=5\n    def inner():\n        return x+1\n    return inner\nprint(outer()())',
                 "e.g. 6", ["6"]),
            _out("Static Method", "Trace the static method call.",
                 'class Util:\n    @staticmethod\n    def double(n): return n*2\nprint(Util.double(4))',
                 "e.g. 8", ["8"]),
            _out("Property Trace", "Trace the property access.",
                 'class C:\n    @property\n    def val(self): return 99\nprint(C().val)', "e.g. 99", ["99"]),
            _out("Exception Chain", "Trace which except block runs.",
                 'try:\n    int("x")\nexcept (ValueError, TypeError):\n    print("handled")',
                 "e.g. handled", ["handled"]),
            _out("Multiple Inheritance", "Trace the MRO resolved method.",
                 'class A:\n    def who(self): return "A"\nclass B:\n    def who(self): return "B"\nclass C(A,B):\n    pass\nprint(C().who())',
                 "e.g. A", ["A"]),
            _out("List Slicing Advanced", "Trace the step slice.",
                 'l = list(range(10))\nprint(l[::2])', "e.g. [0, 2, 4, 6, 8]", ["[0, 2, 4, 6, 8]"]),
            _code("Recursive Vault", "Write a recursive factorial(5) and print it.",
                  'Define recursive function factorial(n) and print(factorial(5)).',
                  "e.g. 120",
                  "def factorial(n):\n    pass\nprint(factorial(5))",
                  lambda stdout, ns: stdout.strip() == "120"),
            _out("Global vs Local", "Trace the scope resolution.",
                 'x = 1\ndef f():\n    x = 2\n    return x\nprint(f(), x)', "e.g. 2 1", ["2 1"]),
            _code("Custom Exception", "Define AccessDenied exception and raise/catch it printing its message.",
                  'class AccessDenied(Exception): pass — raise it with message "denied", catch and print(e).',
                  "e.g. denied",
                  "class AccessDenied(Exception):\n    pass\ntry:\n    raise AccessDenied(\"denied\")\nexcept AccessDenied as e:\n    print(e)",
                  lambda stdout, ns: stdout.strip() == "denied"),
        ],
    },
    "Advanced": {
        1: [
            _out("Decorator with Args", "Trace the parameterized decorator output.",
                 'def repeat(n):\n    def deco(f):\n        def wrap():\n            for _ in range(n): f()\n        return wrap\n    return deco\n@repeat(2)\ndef ping():\n    print("ping")\nping()',
                 "e.g. ping\\nping", ["ping ping"]),
            _out("Generator Expression", "Trace the sum of a generator expression.",
                 'print(sum(x*x for x in range(4)))', "e.g. 14", ["14"]),
            _out("Metaclass Concept", "Trace type() based class check.",
                 'class Agent: pass\nprint(type(Agent) is type)', "e.g. True", ["True"]),
            _out("Threading Concept", "Identify GIL effect (conceptual True/False).",
                 '# CPython GIL allows only one thread to execute Python bytecode at a time.\nprint(True)',
                 "e.g. True", ["True"]),
            _out("Deep vs Shallow Copy", "Trace the shallow copy behavior.",
                 'import copy\na=[[1,2]]\nb=copy.copy(a)\nb[0][0]=99\nprint(a[0][0])', "e.g. 99", ["99"]),
            _out("Args Unpacking", "Trace the unpacked call.",
                 'def add3(a,b,c): return a+b+c\nnums=[1,2,3]\nprint(add3(*nums))', "e.g. 6", ["6"]),
            _out("Dict Unpacking", "Trace the merged dictionary.",
                 'd1={"a":1}\nd2={"b":2}\nprint({**d1, **d2})', "e.g. {'a': 1, 'b': 2}", ["{'a': 1, 'b': 2}"]),
            _code("Custom Iterator", "Build a class Counter that iterates 1,2,3 and print list(Counter()).",
                  'Implement __iter__ and __next__ (StopIteration after 3) then print(list(Counter())).',
                  "e.g. [1, 2, 3]",
                  "class Counter:\n    def __init__(self):\n        self.n = 0\n    def __iter__(self):\n        return self\n    def __next__(self):\n        pass\nprint(list(Counter()))",
                  lambda stdout, ns: stdout.strip() == "[1, 2, 3]"),
            _out("Memoization Trace", "Trace the cached fibonacci call count concept.",
                 'from functools import lru_cache\n@lru_cache\ndef fib(n):\n    return n if n<2 else fib(n-1)+fib(n-2)\nprint(fib(10))',
                 "e.g. 55", ["55"]),
            _out("Type Hints", "Trace annotated function's return.",
                 'def add(a: int, b: int) -> int:\n    return a+b\nprint(add(3,4))', "e.g. 7", ["7"]),
        ],
        2: [
            _out("Regex Groups", "Extract the captured group.",
                 'import re\nm = re.search(r"(\\d+)-(\\d+)", "code-42-99")\nprint(m.group(1))', "e.g. 42", ["42"]),
            _out("JSON Trace", "Trace the parsed JSON value.",
                 'import json\nd = json.loads(\'{"key": "value"}\')\nprint(d["key"])', "e.g. value", ["value"]),
            _out("Comprehension with Condition", "Trace the filtered comprehension.",
                 'print([x for x in range(10) if x % 3 == 0])', "e.g. [0, 3, 6, 9]", ["[0, 3, 6, 9]"]),
            _out("Enum Trace", "Trace the enum member value.",
                 'from enum import Enum\nclass Status(Enum):\n    OK = 1\n    FAIL = 2\nprint(Status.OK.value)',
                 "e.g. 1", ["1"]),
            _out("Abstract Base Class", "Trace which method is required (conceptual).",
                 'from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self): pass\nprint("area")',
                 "e.g. area", ["area"]),
            _out("Context Manager (contextlib)", "Trace the contextlib output.",
                 'from contextlib import contextmanager\n@contextmanager\ndef cm():\n    print("start")\n    yield\n    print("end")\nwith cm():\n    print("mid")',
                 "e.g. start\\nmid\\nend", ["start mid end"]),
            _out("Operator Overload", "Trace the overloaded + operator.",
                 'class V:\n    def __init__(self,x): self.x=x\n    def __add__(self,o): return V(self.x+o.x)\nprint((V(2)+V(3)).x)',
                 "e.g. 5", ["5"]),
            _code("Thread-safe Counter (Concept)", "Simulate a counter increment 5 times in a loop and print total.",
                  'Use a for loop 5 times incrementing a variable count starting at 0, print(count).',
                  "e.g. 5", "count = 0\nfor _ in range(5):\n    pass\nprint(count)",
                  lambda stdout, ns: stdout.strip() == "5"),
            _out("Slicing Assignment", "Trace the in-place slice replacement.",
                 'l=[1,2,3,4,5]\nl[1:3]=[9,9]\nprint(l)', "e.g. [1, 9, 9, 4, 5]", ["[1, 9, 9, 4, 5]"]),
            _out("Walrus Operator", "Trace the assignment expression.",
                 'data=[1,2,3]\nif (n:=len(data)) > 2:\n    print(n)', "e.g. 3", ["3"]),
        ],
        3: [
            _out("Decorator Stack", "Trace the order of stacked decorators.",
                 'def a(f):\n    def w(): print("a"); f()\n    return w\ndef b(f):\n    def w(): print("b"); f()\n    return w\n@a\n@b\ndef base(): print("base")\nbase()',
                 "e.g. a\\nb\\nbase", ["a b base"]),
            _out("Generator Send", "Trace the generator coroutine value.",
                 'def gen():\n    x = yield\n    print("got", x)\ng=gen()\nnext(g)\ng.send(5)',
                 "e.g. got 5", ["got 5"]),
            _out("Metaprogramming", "Trace dynamic attribute creation.",
                 'class A: pass\na=A()\nsetattr(a,"x",10)\nprint(a.x)', "e.g. 10", ["10"]),
            _out("Descriptor Concept", "Trace property setter validation.",
                 'class Temp:\n    def __init__(self): self._v=0\n    @property\n    def v(self): return self._v\n    @v.setter\n    def v(self,val):\n        self._v = val if val>0 else 0\nt=Temp()\nt.v=-5\nprint(t.v)',
                 "e.g. 0", ["0"]),
            _out("Async Concept", "Identify what 'await' pauses (conceptual keyword).",
                 '# await pauses execution until the coroutine completes\nprint("coroutine")',
                 "e.g. coroutine", ["coroutine"]),
            _out("Memory Trace", "Trace identity comparison of small ints.",
                 'a=256\nb=256\nprint(a is b)', "e.g. True", ["True"]),
            _out("Functools Reduce", "Trace the reduced product.",
                 'from functools import reduce\nprint(reduce(lambda x,y: x*y, [1,2,3,4]))', "e.g. 24", ["24"]),
            _code("Final Vault: Class + Decorator", "Combine a class method with a decorator that logs 'unlocked' before returning value 1337.",
                  'Define decorator that prints "unlocked" then calls function; apply to method crack() returning 1337; print(obj.crack()).',
                  "e.g. unlocked\\n1337",
                  "def deco(f):\n    def wrap(*a):\n        print(\"unlocked\")\n        return f(*a)\n    return wrap\n\nclass Vault:\n    @deco\n    def crack(self):\n        return 1337\n\nv = Vault()\nprint(v.crack())",
                  lambda stdout, ns: stdout.strip().splitlines()[-2:] == ["unlocked", "1337"]),
            _out("Exception Groups Concept", "Trace finally block execution order.",
                 'try:\n    print("try")\n    raise ValueError\nexcept ValueError:\n    print("except")\nfinally:\n    print("finally")',
                 "e.g. try\\nexcept\\nfinally", ["try except finally"]),
            _out("The Master Key", "Final trace: full pipeline output.",
                 'nums=[1,2,3,4,5]\nresult=sum(x**2 for x in nums if x%2==1)\nprint(result)',
                 "e.g. 35", ["35"]),
        ],
    },
}


def get_level_questions(difficulty, level):
    return QUESTIONS[difficulty][level]


def get_question(difficulty, level, q_index):
    """q_index is 1-based"""
    return QUESTIONS[difficulty][level][q_index - 1]
